name: Cypress Tests

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps --legacy-peer-deps
    
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        record: false
        config-file: cypress.config.ts
        install: false
      env:
        CI: true
        CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
    
    - name: Upload Cypress Screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
        retention-days: 30

    - name: Upload Cypress Videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos
        retention-days: 30

  # Test matrix para múltiples navegadores (opcional)
  test-matrix:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Run Cypress tests on ${{ matrix.browser }}
      uses: cypress-io/github-action@v6
      with:
        browser: ${{ matrix.browser }}
        install: false

  # Comentario en PRs con resultados
  comment-pr:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Comment PR
      uses: actions/github-script@v7
      with:
        script: |
          const testResult = '${{ needs.test.result }}';
          const emoji = testResult === 'success' ? '✅' : '❌';
          const status = testResult === 'success' ? 'All tests passed' : 'Some tests failed';
          
          const body = `## 🌲 Cypress v15 Test Results
          
          ${emoji} **${status}**
          
          📊 [View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          🔧 **Test Environment:**
          - Cypress: v15.0.0
          - Node.js: LTS
          - Browser: Chrome
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });